"""Trace public/assets/logo.webp into src/components/mascot/paths.ts.

The mascot is the logo hornet itself: this splits the logo into its three parts (wings,
head, abdomen; the wings are separate so they can flap) and each part into colour layers,
then traces every layer with potrace. Rerun it whenever the logo changes:

    pip install pillow numpy scipy   # plus the potrace binary (apt install potrace)
    python3 scripts/trace-mascot.py
"""

import os
import re
import subprocess
import tempfile

import numpy as np
from PIL import Image
from scipy import ndimage as ndi

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGO = os.path.join(ROOT, "public/assets/logo.webp")
OUT = os.path.join(ROOT, "src/components/mascot/paths.ts")

im = np.array(Image.open(LOGO).convert("RGBA")).astype(int)
r, g, b, a = (im[..., i] for i in range(4))
opaque = a >= 128
height = im.shape[0]

ink = ndi.binary_closing(opaque & (r < 120) & (g < 120) & (b < 120), iterations=2)
yellow = opaque & (r > 200) & (g > 200) & (b < 140)
orange = opaque & (r > 200) & (g > 120) & (g < 205) & (b < 150)
white = opaque & (r > 200) & (g > 200) & (b > 200)

# The ink outlines enclose each part; filling them gives one silhouette per part
# (the yellow panel behind the hornet is outside every outline, so it drops out).
silhouette = ndi.binary_fill_holes(ink)
labels, count = ndi.label(silhouette)
parts = []
for i in range(1, count + 1):
    mask = labels == i
    if mask.sum() > 1000:
        cy, cx = ndi.center_of_mass(mask)
        parts.append((cx, cy, mask))
wing = min(parts, key=lambda p: p[0])[2]
body = [p for p in parts if p[2] is not wing]
head = min(body, key=lambda p: p[1])[2]
abdomen = max(body, key=lambda p: p[1])[2]

# (export name, mask). Head and abdomen use their whole silhouette as the yellow base,
# so antialiased edges never show through as white specks.
LAYERS = [
    ("WING_BASE", wing),
    ("WING_INK", wing & ink),
    ("HEAD_YELLOW", head),
    ("HEAD_ORANGE", head & orange & ~ink),
    ("HEAD_WHITE", head & white & ~ink),
    ("HEAD_INK", head & ink),
    ("ABDOMEN_YELLOW", abdomen),
    ("ABDOMEN_ORANGE", abdomen & orange & ~ink),
    ("ABDOMEN_INK", abdomen & ink),
]


def trace(mask, tmp):
    pbm = os.path.join(tmp, "layer.pbm")
    svg = os.path.join(tmp, "layer.svg")
    Image.fromarray(((~mask) * 255).astype(np.uint8)).convert("1").save(pbm)
    subprocess.run(
        ["potrace", pbm, "-s", "-u", "1", "-t", "8", "-a", "1", "-O", "0.6", "--flat", "-o", svg],
        check=True,
    )
    paths = re.findall(r' d="([^"]+)"', open(svg).read())
    return " ".join(" ".join(paths).split())


lines = [
    "// Generated by scripts/trace-mascot.py from public/assets/logo.webp: one path per part",
    f"// and colour, in the logo's pixel space ({height} x {height}, y flipped: see MASCOT_FLIP).",
    "// Regenerate rather than hand-edit, so the mascot stays identical to the logo hornet.",
    "",
    f'export const MASCOT_FLIP = "translate(0 {height}) scale(1 -1)";',
    "",
]
with tempfile.TemporaryDirectory() as tmp:
    for name, mask in LAYERS:
        lines += [f"export const {name} =", f'    "{trace(mask, tmp)}";', ""]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("wrote", os.path.relpath(OUT, ROOT))
